microlinkhq/sdk

package.json
src/components/Card/index.js

Just some missing props from the `CardProps` type, as well as assigning the `State` type to the components inner `state`
Also removed the `logo` thing you added, as you said this wasn't in-use right?

Flow-related fixes

---

package.json
src/components/Card/index.js

Add `whatwg-fetch` polyfill

---

stories/index.js

+ Fix width/height stories (wrong way around)
+ Add nesting to storybook
+ Misc. renaming on stories

Restructure storybook

---

package.json
src/components/Card/index.js
stories/index.js

+ Remove the `whatwg-fetch` polyfill dependency
+ Added `unfetch` as devDependency
+ Use `unfetch` polyfill in storybook stories
(As discussed in #8)

Remove fetch polyfill dependency (read desc.)

---

src/components/Card/CardWrap.js

+ Props aren’t read in styled-components `css` method

Fix createElement’s element

---

packages/react-microlink/src/index.js
packages/react-microlink/src/utils/index.js
packages/react-microlink/stories/index.js

Add image prop support

---

packages/react-microlink/src/index.js

We should `componentDidMount` instead of `componentWillMount` to render a component from server side that need to fetch data content.

Fix server side support

---

packages/react-microlink/src/components/Card/CardEmptyState.js
packages/react-microlink/src/components/Card/CardMedia/image.js
packages/react-microlink/src/components/Card/CardMedia/index.js
packages/react-microlink/src/components/Card/CardMedia/loader.js
packages/react-microlink/src/components/Card/CardMedia/video.js
packages/react-microlink/src/components/Card/CardMedia/wrap.js
packages/react-microlink/src/components/Card/CardWrap.js

Close #28 
Inspired by https://github.com/Astrocoders/react-image-smooth-loading

Smooth image load

---

packages/microlinkjs/config/webpack.config.dev.js
packages/microlinkjs/config/webpack.config.prod.js
packages/microlinkjs/package.json
packages/microlinkjs/public/index.html
packages/react-microlink/package.json

As described here: https://www.styled-components.com/docs/faqs#i-am-a-library-author-should-i-bundle-styledcomponents-with-my-library

Move styled-components to peerDependency

---

packages/react-microlink/package.json
packages/react-microlink/src/components/Card/CardText.js
packages/react-microlink/src/components/Card/CardWrap.js
packages/react-microlink/stories/data.js
packages/react-microlink/stories/index.js

I was thinking not have too sense mix style props with the component API

Remove `round` prop

---

packages/microlinkjs/public/index.html
packages/microlinkjs/src/index.js

Ability to pass DOM selector

---

packages/react-microlink/src/index.js

This will always have the component query the server no matter what options are passed in, but allow you to override individual attributes like title, description, image, url, etc.

Merged fetched data with provided overrides

---

packages/react-microlink/package.json
packages/react-microlink/src/components/Card/CardMedia/Image.js

Close #116
Waiting response from Hootsuite team:
https://twitter.com/Kikobeats/status/1001378627559313408

Ensure Card image is over HTTPS

---

packages/react-microlink/package.json
packages/react-microlink/src/components/Card/CardEmpty.js
packages/react-microlink/src/components/Card/CardMedia/Image.js
packages/react-microlink/src/components/Card/CardMedia/Video/index.js
packages/react-microlink/src/index.js

Upgrade styled-components (v4)

---

packages/react/.babelrc
packages/react/.storybook/addons.js
packages/react/.storybook/config.js
packages/react/__test__/__snapshots__/stories.test.js.snap
packages/react/__test__/stories.test.js
packages/react/package.json
packages/react/src/index.js
packages/react/stories/index.js
packages/vanilla/config/webpack.config.prod.js
packages/vanilla/package.json

BREAKING CHANGE : it supports pass a function as mapper

feat: rename data → setData

---

packages/react/__test__/__snapshots__/stories.test.js.snap
packages/react/src/components/Card/CardMedia/Video/index.js
packages/react/src/components/Card/CardMedia/index.js
packages/react/src/components/Card/CardWrap.js
packages/react/src/index.js
packages/vanilla/package.json
packages/vanilla/rollup.config.js
packages/vanilla/src/index.js

build: rename loading → isLoading internally

---

packages/react/src/components/Card/CardText.js
packages/react/src/utils/index.js
packages/vanilla/src/index.js

refactor & tweaks

---

packages/react/.storybook/config.js
packages/react/__test__/__snapshots__/stories.test.js.snap
packages/react/package.json
packages/react/src/components/Card/CardEmpty.js
packages/react/src/components/Card/CardMedia/index.js
packages/react/src/components/Card/CardWrap.js
packages/react/src/index.js
packages/react/src/utils/hooks.js
packages/react/src/utils/index.js
packages/react/stories/createStoryEntry.js
packages/react/stories/index.js

closes #139 
This is a very WIP version of this @Kikobeats, just wanted to get something up here.
I've had to skip husky verification on committing because there seems to be an error with the linter config (?):
```sh
Could not parse lint-staged config.
Error: ● Validation Error:
Invalid value for 'linters'.
Advanced configuration has been deprecated. For more info, please visit: https://github.com/okonet/lint-staged.
Configured value is: {'*.js': ['prettier-standard', 'git add'], 'package.json': ['finepack', 'git add']}
Please refer to https://github.com/okonet/lint-staged#configuration for more information...
```

IntersectionObserver API integration

---

packages/react/src/utils/index.js

fix: ensure window is accesible

---

packages/react/src/components/Card/CardMedia/Video/controls.js
packages/react/src/components/Card/CardMedia/Video/index.js

Fix video `useRef` hook

---

packages/react/__test__/__snapshots__/stories.test.js.snap
packages/react/src/components/Card/CardContent.js
packages/react/src/components/Card/CardEmpty.js
packages/react/src/components/Card/CardMedia/Video/controls.js
packages/react/src/components/Card/CardMedia/loader.js
packages/react/src/components/Card/CardMedia/wrap.js
packages/react/src/components/Card/CardText.js
packages/react/src/index.js
packages/react/src/utils/index.js
packages/react/stories/createStoryEntry.js

Mini card size

---

packages/react/src/index.js
packages/react/src/utils/index.js
packages/react/stories/__snapshots__/stories.test.js.snap
packages/react/stories/index.js

This PR fix a little bug related to `media` order that isn't been respected.
Now, if the payload includes `video` and `audio`, the media mounted will be the first appeared at `media`.

fix: respect media priorities

---

.gitignore
README.md
packages/angular/.prettierrc
packages/angular/.storybook/config.js
packages/angular/.storybook/main.js
packages/angular/.storybook/tsconfig.json
packages/angular/angular.json
packages/angular/index.d.ts
packages/angular/ng-package.json
packages/angular/package.json
packages/angular/src/index.ts
packages/angular/src/microlink/index.ts
packages/angular/src/microlink/microlink.component.ts
packages/angular/src/microlink/microlink.module.ts
packages/angular/stories/index.ts
packages/angular/tsconfig.json

Add Angular Integration

---

packages/angular/package.json
packages/angular/src/microlink/index.ts
packages/angular/stories/index.ts

+ Update Angular package.json `typings` path
+ Rename Angular package's `module` and `component` exports
+ Re-order Angular package.json properties

Update angular types + exports

---

packages/angular/package.json
packages/angular/tsconfig.json

+ Disable Angular ivy engine (https://angular.io/guide/ivy#maintaining-library-compatibility)
+ Bump typescript version

build: disable ivy for angular

---

.travis.yml
packages/react/package.json
packages/react/src/index.js

feat: add fetchData parameter

---

packages/react/package.json
packages/react/src/components/Card/CardMedia/Controls/index.js
packages/react/src/context/GlobalState.js
packages/react/src/index.js
packages/react/stories/__snapshots__/stories.test.js.snap
packages/react/stories/index.js

+ Add new `mediaRef` prop for interacting with the media element
+ Add basic storybook example of `mediaRef` prop

build: add mediaRef prop

---

packages/hover-vanilla/src/index.js
packages/react/src/index.js

Already done at hover/vanilla but I feel it could be a good react default

build: setup a sensible more complete media default

---

packages/hover-react/.storybook/main.js
packages/hover-react/package.json
packages/hover-react/rollup.config.js
packages/hover-vanilla/package.json
packages/hover-vanilla/rollup.config.js
packages/react/package.json
packages/react/rollup.config.js
packages/vanilla/package.json
packages/vanilla/rollup.config.js

Something breaks the bundle after merged: https://github.com/microlinkhq/sdk/pull/292
Trying to figure out the thing

test: ensure bundle is working

---

packages/hover-vanilla/package.json
packages/hover-vanilla/src/index.js
packages/react/package.json
packages/react/src/utils/index.js

instead of is-localhost-url since it's deprecated

refactor: use localhost-url-regex
