microlinkhq/sdk

package.json
Close #29, bug in rxjs has been fixed in 5.5.4 release
=> Re-enable precommit script in package.json

packages/react-microlink/package.json, packages/react-microlink/src/components/Card/CardContent.js, packages/react-microlink/src/components/Card/CardEmptyState.js, packages/react-microlink/src/index.js, packages/react-microlink/src/utils/index.js, packages/react-microlink/stories/index.js
- A lot of definitions around the code. 
- The library is too simple for the flow user case.
- Added `prop-types` as dev dependency.
- prettier-standard is not working well with flow and babel language extension.
- Fixed a bug related with `microlink__card` class.
=> Use prop-types instead of flow

README.md, packages/microlinkjs/public/index.html, packages/microlinkjs/src/index.js
I found a clean way to do that using [dataset](https://caniuse.com/#search=dataset), and looks with enough compatibility.
Closes https://github.com/microlinkhq/microlinkjs/issues/39
=> UMD: Add support for inline data attributes

packages/react-microlink/.storybook/addons.js, packages/react-microlink/.storybook/config.js, packages/react-microlink/package.json, packages/react-microlink/src/components/Card/CardContent.js, packages/react-microlink/src/components/Card/CardEmptyState.js, packages/react-microlink/src/components/Card/CardImage.js, packages/react-microlink/src/components/Card/CardLarge.js, packages/react-microlink/src/components/Card/CardWrap.js, packages/react-microlink/src/utils/index.js
Fix #37
I added responsive (mobile) style for normal and large card.
Also I added viewport storybook for be possible visualize it 😄
The only TODO before merge it is how to convert the three lines empty state into one under mobile viewport. any idea, @breadadams?
=> Improve responsive

packages/react-microlink/package.json, packages/react-microlink/src/components/Card/CardContent.js, packages/react-microlink/src/components/Card/CardEmptyState.js, packages/react-microlink/src/components/Card/CardWrap.js
before (only on browser with webkit support)
after (crossbrowser)
I'm considering use https://github.com/tjindapitak/react-text-ellipsis for that, it supports css and js as fallback solution, I need to check the bundle size implications but could be worth it.
=> Add three lines clamp cross browser

packages/react-microlink/package.json, packages/react-microlink/src/index.js, packages/react-microlink/stories/index.js
This PR adds the possibility to load the Card content from a `data` property, instead of fetching the data again.
Useful when you need do a microlink API call and you want to use the data provided as card.
Actually it only add one line more, the rest is refactoring
=> Add data property

packages/react-microlink/stories/index.js
Some minor adjustments to the naming of the "video media" & "image prop" stories
=> Rename image/video stories

packages/react-microlink/src/index.js
Correct me if I'm mistaken, but I think this propType is deprecated?
=> Remove `apiEndpoint` propType

packages/react-microlink/src/components/Card/CardMedia/image.js, packages/react-microlink/src/components/Card/CardWrap.js
After reading your recent suggestion @Kikobeats (https://github.com/microlinkhq/microlinkjs/pull/72#pullrequestreview-98148844), I see it better-structured this way. So I've moved some of the other style blocks to follow suit.
=> Move prop-dependent styles to variables

packages/react-microlink/lib/components/Card/CardContent.js, packages/react-microlink/package.json, packages/react-microlink/src/components/Card/CardContent.js, packages/react-microlink/src/components/Card/CardText.js, packages/react-microlink/src/components/Card/CardWrap.js
`ClampLines` wraps its content within another `div`, our responsive overflow styles aren't affecting it.
Before:
After:
=> Adjust card text overflow/ellipsis control

package.json
+ Adjust order of clean’s commands, currently it only works if `eachdir` is globally installed (because it gets removed in the first step)
=> Fix `clean` package script

packages/react-microlink/package.json, packages/react-microlink/src/components/Card/CardContent.js, packages/react-microlink/stories/data.js
do the same using native `URL` and strip www
I note we can remove this dependency after read normalize-url implementation:
https://github.com/sindresorhus/normalize-url/blob/master/index.js#L118
Also I added `https://xn--vi8hl0c.ws/` into tests urls to keep in mind we don't convert from IDN to unicode:
https://github.com/sindresorhus/normalize-url/blob/master/index.js#L112
This could be done adding punycode or similar dependency, but it's a little heavy (https://bundlephobia.com/result?p=punycode@2.1.0) so I want investigate and found a workaround first
=> Remove extract-domain dependency

packages/microlinkjs/src/index.js
=> Support single node as argument to microlink()

packages/react/src/components/Card/CardMedia/wrap.js, packages/vanilla/package.json
=> fix: use transparent background for png images

packages/react/src/components/Card/CardMedia/Controls/SeekButton.js
=> fix: prevent pass cardSize as DOM property

packages/react/src/components/Card/CardMedia/Video.js, packages/react/src/utils/index.js
images.weserv.nl releases API v5 and they are serving around 6 millions request per hour. That's totally crazy!
I think it's enough stable and confident to be used as default image proxy.
On this PR:
- Enable image proxy for any http(s) URL.
- Setup [compression level](https://images.weserv.nl/docs/format.html#compression-level) to max possible.
- Setup [adaptative filter](https://images.weserv.nl/docs/format.html#adaptive-filter) for PNGs images.
- Setup [progressive filter](https://images.weserv.nl/docs/format.html#interlace-progressive) for GIF/JPEG images
=> build: enable image proxy for any https url

packages/react/src/index.js, packages/react/src/utils/index.js, packages/react/stories/__snapshots__/stories.test.js.snap, packages/react/stories/createStoryEntry.js, packages/react/stories/data.js, packages/react/stories/index.js
=> feat: add iframe support

packages/react/src/components/Card/CardContent.js, packages/react/src/components/Card/CardEmpty.js, packages/react/src/components/Card/CardMedia/Audio.js, packages/react/src/components/Card/CardMedia/Controls/index.js, packages/react/src/components/Card/CardMedia/Image.js, packages/react/src/components/Card/CardMedia/Video.js, packages/react/src/components/Card/CardMedia/Wrap.js, packages/react/src/components/Card/CardMedia/index.js, packages/react/src/components/Card/CardMedia/loader.js, packages/react/src/components/Card/CardWrap.js, packages/react/src/context/GlobalState.js, packages/react/src/index.js, packages/react/stories/__snapshots__/stories.test.js.snap, packages/react/stories/index.js
Hey @Kikobeats, there are a couple of tweaks/fixes in this PR, but the main one is the implementation of the `createContext` API.
This allows us to easily share props and data globally across the library without such a large chain of passing them down to children. In doing so it seems I've actually resolved #95:
___
Another issue resolved is with the image loader overlay, I'm not sure when exactly (because it _used_ to work) but the boolean was flipped, and the overlay was never shown.
=> Implement React Context API

packages/react/src/components/Card/CardContent.js, packages/react/src/components/Card/CardMedia/Controls/FooterControls.js, packages/react/src/components/Card/CardMedia/Controls/MediaButton.js, packages/react/src/components/Card/CardMedia/Controls/ProgressBar.js, packages/react/src/components/Card/CardMedia/Controls/index.js, packages/react/src/components/Card/CardWrap.js, packages/react/stories/__snapshots__/stories.test.js.snap
Associated `will-change` targeting CSS properties that are going to change as a way to tell browser it can optimize them.
Also, I removed some transition that actually they are not being used.
=> perf: optimize animation with will-change

packages/vanilla/src/index.js
This change is motivated since the vanilla version needs to mount the microlink card into the node selected using a dom query selector.
On the other hand, Vue/Angular needs to reuse the same node.
So the thing I did is to remove the rootNode logic out of the vanilla bundle, meaning:
- The node used for mounting the component will be `rootNode || el`
- For reusing the mounted node, just setup the logic **before** and **after** call vanilla bundle.
This PR is not completed; Need to update the Vue/Angular logic for doing that workflow:
1) Create `rootNode` and pass it to `microlink/vanilla`.
2) do cleanup action (`el.remove()` after exec `microlink/vanilla`.
=> build: move rootNode logic out of vanilla

packages/react/src/components/Card/CardWrap.js, packages/react/stories/__snapshots__/stories.test.js.snap
so `styled-components` is showing this warning:
```
styled-components.browser.esm.js:1347 The component styled.a with the id of "sc-pRtAn" has been created dynamically.
You may see this warning because you've called styled inside another component.
To resolve this only create new StyledComponents outside of any render method and function component
```
and it's correct, we were creating the element dynamically, so I refactor it to take the advantages of `as` prop tag 🙂
=> fix: avoid create element dynamically

packages/angular/src/microlink/microlink.component.ts, packages/vue/src/index.js
+ Add `as` prop to Vue & Angular integrations, to ensure cards render as links
+ Rename vue "parameters" → "options"
=> Add `as` prop to Vue & Angular integrations

packages/react/package.json, packages/react/src/index.js
It's used for obtaining the Microlink API URL
https://github.com/microlinkhq/sdk/blob/9e5d634bb0951e21786338df7e5ec8b99e34d5aa/packages/react/src/index.js#L51
Since it isn't more necessary after that, it's preferable to don't pass it around components to avoid leaked it accidentally.
Also, because the default value is `undefined`, react warns users about that:
> Warning: React does not recognize the `apiKey` prop on a DOM element. If you intentionally want it to appear in the DOM as a custom attribute, spell it as lowercase `apikey` instead. If you accidentally passed it from a parent component, remove it from the DOM element.
closes #276
=> fix: avoid to pass apikey

packages/react/src/index.js
These changes are motivated by Next.js linter:
```
$ npx next lint
./src/index.js
101:6  Warning: React Hook useCallback has missing dependencies: 'apiUrlProps', 'fetchData', and 'mergeData'. Either include them or remove the dependency array.  react-hooks/exhaustive-deps
101:38  Warning: React Hook useCallback has a complex expression in the dependency array. Extract it to a separate variable so it can be statically checked.  react-hooks/exhaustive-deps
156:5  Warning: React Hook useCallback has a missing dependency: 'updateState'. Either include it or remove the dependency array.  react-hooks/exhaustive-deps
159:3  Warning: React Hook useEffect has a missing dependency: 'toFetchData'. Either include it or remove the dependency array.  react-hooks/exhaustive-deps
```
Related: …
=> fix: linter warnings

packages/react/src/index.js
The changes introduced in https://github.com/microlinkhq/sdk/pull/296 are causing the component doesn't change the state, it looks like inifite loading.
**How to reproduce**
1. clone https://github.com/microlinkhq/www
2. install the deps (pnpm install)
3. link your local `@microlink/sdk@5.5.13` with the site
4. run the site (npm run dev) and visit a route that uses the component (.e.g, `http://localhost:8000/docs/sdk/parameters/url`)
=> fix: infinite loading
